### ISSUE TITLE
openresty warnings

### ISSUE THREAD

**Issue by jave** [emazzotta/docker-nginx-more-headers-lua#3]
At the moment I'm using your image for the more-headers module, but I would also like to use the lua module eventually. Are these warnings significant?

2020/02/03 09:08:03 [alert] 1#0: detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
2020/02/03 09:08:03 [error] 1#0: lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file './resty/core.lua'
	no file '/usr/local/share/luajit-2.0.5/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core/init.lua'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so')
nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file './resty/core.lua'
	no file '/usr/local/share/luajit-2.0.5/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core/init.lua'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so')

**Comment by emazzotta** [comment]
Yes, I can reproduce this issue.

I'm not using LuaJIT anymore, so if you're willing to fix the issue I'm more than happy to accept PRs.

**Comment by emazzotta** [comment]
Hi @jave 

I've decided to ditch LuaJit given it doesn't fit my use case anymore and to get rid of this message. 

If you want to use LuaJit I recommend using Openresty. In case you want to use both LuaJit and headers-more, you'll likely need to compile your own nginx from scratch (it can be tricky to configure LuaJit, OpenSSL etc. I've tried but didn't get it working).

**Comment by emazzotta** [comment]
FYI, as of today, LuaJIT is reintroduced. 🎉
